package org.openmrs.module.chuschedules.generator;

/**
 * What to do with one previously generated block when its template's pattern has changed.
 */
public enum RefreshDecision {
	
	/** Not ours to touch yet, or ever: the date is today or earlier. */
	LEAVE_PAST,
	
	/** The block is gone already; drop our stale provenance row so the date can regenerate. */
	ALREADY_GONE,
	
	/** A patient is booked. Leave the clinic exactly as it is and tell a human. */
	KEEP_BOOKED,
	
	/** Future, generated by us, and empty: safe to void so it can be regenerated. */
	VOID
}
