package org.openmrs.module.chuschedules.api;

import java.util.Date;
import java.util.List;

import org.openmrs.Provider;
import org.openmrs.annotation.Authorized;
import org.openmrs.api.OpenmrsService;
import org.openmrs.module.chuschedules.ChuSchedulesConstants;
import org.openmrs.module.chuschedules.GeneratedBlock;
import org.openmrs.module.chuschedules.ScheduleException;
import org.openmrs.module.chuschedules.ScheduleTemplate;
import org.openmrs.module.chuschedules.generator.GenerationReport;
import org.openmrs.module.chuschedules.generator.RefreshReport;
import org.springframework.transaction.annotation.Transactional;

@Transactional
public interface ChuSchedulesService extends OpenmrsService {
	
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	ScheduleTemplate saveTemplate(ScheduleTemplate template);
	
	@Transactional(readOnly = true)
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	ScheduleTemplate getTemplate(Integer templateId);
	
	@Transactional(readOnly = true)
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	ScheduleTemplate getTemplateByUuid(String uuid);
	
	@Transactional(readOnly = true)
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	List<ScheduleTemplate> getAllTemplates(boolean includeVoided);
	
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	ScheduleTemplate voidTemplate(ScheduleTemplate template, String reason);
	
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	ScheduleException saveException(ScheduleException exception);
	
	@Transactional(readOnly = true)
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	List<ScheduleException> getExceptions(Date from, Date to, Provider provider);
	
	@Transactional(readOnly = true)
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	List<ScheduleException> getAllExceptions(boolean includeVoided);
	
	@Transactional(readOnly = true)
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	ScheduleException getException(Integer exceptionId);
	
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	ScheduleException voidException(ScheduleException exception, String reason);
	
	@Transactional(readOnly = true)
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	List<GeneratedBlock> getGeneratedBlocks(ScheduleTemplate template, Date from, Date to);
	
	/**
	 * Creates appointment blocks for every occurrence of the template between the two dates, or
	 * reports what it would create. Generation never touches the past, never overlaps a block that
	 * already exists, and never produces the same occurrence twice. Pass {@code dryRun} true to
	 * preview: the same code runs, only the write is suppressed.
	 */
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	GenerationReport generate(ScheduleTemplate template, Date from, Date to, boolean dryRun);
	
	/**
	 * Voids the future blocks this module generated for a template, so they can be regenerated
	 * under a changed pattern. Only touches blocks that are in the future, were generated by this
	 * module, and have no live appointments. Anything booked is left exactly as it is and reported
	 * back, for a human to resolve with the patient. Blocks entered by hand are never candidates:
	 * they are not in chu_generated_block.
	 */
	@Authorized(ChuSchedulesConstants.PRIVILEGE_MANAGE)
	RefreshReport refreshFutureBlocks(ScheduleTemplate template, String reason);
}
